### ISSUE TITLE
Read with iterator

### ISSUE THREAD

**Issue by sonic182** [juancarlospaco/faster-than-csv#4]
Would be nice to read csv having an iterator

**Comment by verdug0** [comment]
Oh, so, you can not read the entire file?
There is no such thing implemented yet? Are you sure?

**Comment by sonic182** [comment]
Yes, there is no method yielding rows

**Comment by juancarlospaco** [comment]
This is not supported by design. It is designed to get the CSV data as fast as possible.

This is not effective because sending arguments and returns to/from "C world" into "Python world" has overhead,
but if you have that overhead on each line like it would with an iterator it will be slower,
basically worse than standard library, if you need that use standard library.
Sorry. 🤷‍♀️
