### ISSUE TITLE
It's 3x slower than pandas for larger files

### ISSUE THREAD

**Issue by kootenpv** [juancarlospaco/faster-than-csv#9]
It would be a good idea to include a benchmark with larger, more heterogenous data.

**Comment by juancarlospaco** [comment]
Provide full repro code and minimal sample data.

**Comment by kootenpv** [comment]
Please search on github for csv files larger than 50mb, plenty of examples (in my phone)

**Comment by juancarlospaco** [comment]
No I meant to provide full repro code, and a minimal tiny sample data,
I dont want the repo to become slow harder to clone because of sample data,
but I am more interested on the code that you are using to debug the bug.

Also maybe now other libs have improved, when this lib started, it was a lot faster than others,
also required no dependencies, while other had tons of dependencies, if other libs improved good for them.

**Comment by kootenpv** [comment]
Ah my bad. I just compared:

`csv2list` (3s) against `pd.read_csv` (1s) for a 80MB file of data (cannot share)

**Comment by juancarlospaco** [comment]
Try the new version should be a little better:
`sudo pip3 install faster-than-csv==edca7e6 --no-binary :all: `
You can pass the `columns` count argument to get a little bit better performance, or leave it as `0` otherwise.
